<form class="modal modal-form" onsubmit="submitHandler(event)" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Form</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">      
         <div class="form-group">
            <label class="form-label">Parent</label>
            <select name="parent_id" class="form-control" >

            </select>
        </div>
        <div class="form-group">
            <label class="form-label">Code</label>
            <input type="text" name="code" placeholder="Enter Code Category" class="form-control"  /> 
        </div>
        <div class="form-group">        
            <label class="form-label">Category</label>
            <input type="text" name="name" placeholder="Enter Category" class="form-control"  /> 
            <input type="hidden" name="id" />
        </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Save changes</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</form>