<?= $this->extend('layouts/login.phtml') ?>
<?= $this->section('content') ?>
        <section class="bg-login">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-sm-12">
                        <div class="wrapper-page">
                            <div class="account-pages">
                                <div class="account-box">
                                    <div class="card m-b-30">
                                        <div class="card-body">
                                            <div class="card-title text-center">
                                                <img src="<?php echo base_url('admin');?>/assets/images/logo_sm_2.png" alt="" class="">
                                                <h5 class="mt-3"><b>Welcome to Sae Commerce</b></h5>
                                                <div class="alert alert-danger d-none">test</div>
                                            </div>  
                                            <form class="form mt-5 contact-form" action="index.html" onsubmit="handlerSubmit(event)">
                                                <div class="form-group ">
                                                    <div class="col-sm-12">
                                                        <input class="form-control form-control-line" name="username" type="text" placeholder="Username" required="required">
                                                    </div>
                                                </div>
                                                <div class="form-group ">
                                                    <div class="col-sm-12">
                                                        <input class="form-control form-control-line" name="password" type="password" placeholder="Password" required="required">
                                                    </div>
                                                </div>

                                                <div class="form-group">
                                                    <div class="col-12">
                                                        <label class="cr-styled">
                                                            <input type="checkbox" checked>
                                                            <i class="fa"></i> 
                                                            Remember me
                                                        </label>
                                                    </div>
                                                </div>
                                                
                                                <div class="form-group">
                                                    <div class="col-sm-12 mt-4">
                                                        <button class="btn btn-primary btn-block" type="submit">Log In</button>
                                                    </div>
                                                </div>

                                                <div class="form-group">
                                                    <div class="col-sm-12 mt-4 text-center">
                                                        <a href="recoverpw.html"><i class="fa fa-lock m-r-5"></i> Forgot password?</a>
                                                    </div>
                                                </div>

                                                
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
<?= $this->endSection() ?>

<?= $this->section('js') ?>
    <script type="text/javascript" src="<?php echo base_url('modules/administrator/login/index.js');?>"></script>
<?= $this->endSection() ?>