<form class="modal modal-form" onsubmit="submitHandler(event)" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <input type="hidden" name="id"/>
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Form</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">      
         <div class="form-group">
            <label class="form-label">Image</label>
            <input type="file" name="image" class="form-control"/>
        </div>
        <div class="form-group">
            <label class="form-label">Category</label>
            <select class="form-control select2 custome-select" name="id_product_category">
              
            </select>
        </div>
        <div class="form-group">
            <label class="form-label">Currency</label>
            <select class="form-control select2 custome-select" name="id_currency">
              
            </select>
        </div>
        <div class="form-group">
            <label class="form-label">Name</label>
            <input type="text" name="name" class="form-control"/>
        </div>
        <div class="form-group">
            <label class="form-label">Price sale</label>
            <input type="text" name="price_sale" class="form-control"/>
        </div>
        <div class="form-group">
            <label class="form-label">Price purchase</label>
            <input type="text" name="price_purchase" class="form-control"/>
        </div>
        <div class="form-group">
            <label class="form-label">Description</label>
            <textarea name="description" class="form-control" name="description"></textarea>
        </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Save changes</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</form>