<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="Mannat Themes">
        <meta name="keyword" content="">

        <title>SYNTRA | Responsive Web App Kit</title>

        <!-- Theme icon -->
        <link rel="shortcut icon" href="<?php echo base_url('admin');?>/assets/images/favicon.ico">

        <link href="<?php echo base_url('admin');?>/assets/plugins/morris-chart/morris.css" rel="stylesheet">
        <!-- Theme Css -->
        <link href="<?php echo base_url('admin');?>/assets/css/bootstrap.min.css" rel="stylesheet">
        <link href="<?php echo base_url('admin');?>/assets/css/slidebars.min.css" rel="stylesheet">
        <link href="<?php echo base_url('admin');?>/assets/css/icons.css" rel="stylesheet">
        <link href="<?php echo base_url('admin');?>/assets/css/menu.css" rel="stylesheet" type="text/css">
        <link href="<?php echo base_url('admin');?>/assets/css/style.css" rel="stylesheet">
    </head>

    <body class="sticky-header">
        <section>
            <!-- sidebar left start-->
            <?php echo $this->include('includes/administrator/sidebarleft.php');?>
            <!-- sidebar left end-->

            <!-- body content start-->
            <div class="body-content">
                <!-- header section start-->
                    <?php echo $this->include('includes/administrator/header.php');?>
                <!-- header section end-->
                <?php echo $this->renderSection('content');?>
                <!--end container-->

                <!--footer section start-->
                <footer class="footer">
                    2018 &copy; Syntra.
                </footer>
                <!--footer section end-->


                <!-- Right Slidebar start -->
                    <?php echo $this->include('includes/administrator/sidebarright.php');?>
                <!--end Right Slidebar-->
            </div>
            <!--end body content-->
        </section>


        <script type="text/javascript">
            const baseApi = "<?php echo base_url('api');?>"
            const baseUrl = "<?php echo base_url();?>"
        </script>

        <!-- jQuery -->
        <script src="<?php echo base_url('admin');?>/assets/js/jquery-3.2.1.min.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/js/popper.min.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/js/bootstrap.min.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/js/jquery-migrate.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/js/modernizr.min.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/js/jquery.slimscroll.min.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/js/slidebars.min.js"></script>

        <!--plugins js-->
        <script src="<?php echo base_url('admin');?>/assets/plugins/counter/jquery.counterup.min.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/plugins/waypoints/jquery.waypoints.min.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/plugins/sparkline-chart/jquery.sparkline.min.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/pages/jquery.sparkline.init.js"></script>

        <script src="<?php echo base_url('admin');?>/assets/plugins/chart-js/Chart.bundle.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/plugins/morris-chart/raphael-min.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/plugins/morris-chart/morris.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/pages/dashboard-init.js"></script>


        <!--app js-->
        <script src="<?php echo base_url('admin');?>/assets/js/jquery.app.js"></script>
    </body>
</html>
