<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="Mannat Themes">
        <meta name="keyword" content="">

        <title>SYNTRA | Responsive Web App Kit</title>

        <!-- Theme icon -->
        <link rel="shortcut icon" href="<?php echo base_url('admin');?>/assets/images/favicon.ico">

        <link href="<?php echo base_url('admin');?>/assets/plugins/morris-chart/morris.css" rel="stylesheet">
        <!-- Theme Css -->
        <link  rel="stylesheet" type="text/css"  href="<?php echo base_url();?>/toastify/src/toastify.css"/>
        <link href="<?php echo base_url('admin');?>/assets/css/bootstrap.min.css" rel="stylesheet">
        <link href="<?php echo base_url('admin');?>/assets/css/slidebars.min.css" rel="stylesheet">
        <link href="<?php echo base_url('admin');?>/assets/css/icons.css" rel="stylesheet">
        <link href="<?php echo base_url('admin');?>/assets/plugins/clockpicker/jquery-clockpicker.min.css" rel="stylesheet" />
        <link href="<?php echo base_url('admin');?>/assets/css/menu.css" rel="stylesheet" type="text/css">
        <link href="<?php echo base_url('admin');?>/assets/css/style.css" rel="stylesheet">
        <link href="<?php echo base_url('admin');?>/assets/plugins/jquery-multi-select/multi-select.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo base_url('admin');?>/assets/plugins/select2/select2.min.css" rel="stylesheet" type="text/css" />
    </head>

    <body class="sticky-header">
        <section>
            <!-- sidebar left start-->
            <?php echo $this->include('includes/administrator/sidebarleft.php');?>
            <!-- sidebar left end-->

            <!-- body content start-->
            <div class="body-content">
                <!-- header section start-->
                    <?php echo $this->include('includes/administrator/header.php');?>
                <!-- header section end-->
                <?php echo $this->renderSection('content');?>
                <!--end container-->

                <!--footer section start-->
                <footer class="footer">
                    2018 &copy; Syntra.
                </footer>
                <!--footer section end-->


                <!-- Right Slidebar start -->
                    <?php echo $this->include('includes/administrator/sidebarright.php');?>
                <!--end Right Slidebar-->
            </div>
            <!--end body content-->
        </section>


        <script type="text/javascript">
            const baseApi = "<?php echo base_url('api');?>"
            const baseUrl = "<?php echo base_url();?>"
            const config = {
                headers:{
                    Authorization:`Bearer ${localStorage.getItem('token')}`
                }
            }
        </script>
        
     
        <!-- jQuery -->
        <script src="<?php echo base_url('/');?>/axios/dist/axios.min.js"></script>
        <script src="<?php echo base_url();?>/toastify/src/toastify.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/js/jquery-3.2.1.min.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/js/popper.min.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/js/bootstrap.min.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/js/jquery-migrate.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/js/modernizr.min.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/js/jquery.slimscroll.min.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/js/slidebars.min.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/plugins/responsive-table/js/rwd-table.min.js" type="text/javascript"></script>
      

        <script src="<?php echo base_url('admin');?>/assets/plugins/timepicker/moment.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/plugins/clockpicker/jquery-clockpicker.min.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/plugins/tagsinput/jquery.tagsinput.min.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/plugins/switchery/switchery.min.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/plugins/toggles/toggles.min.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/plugins/timepicker/tempusdominus-bootstrap-4.js"></script>
        <script src="<?php echo base_url('admin');?>/assets/plugins/timepicker/bootstrap-material-datetimepicker.js"></script>
        <!--colorpcker-->
        <script src="<?php echo base_url('admin');?>/assets/plugins/colorpicker/jquery-asColor.js" type="text/javascript"></script>
        <script src="<?php echo base_url('admin');?>/assets/plugins/colorpicker/jquery-asGradient.js" type="text/javascript"></script>
        <script src="<?php echo base_url('admin');?>/assets/plugins/colorpicker/jquery-asColorPicker.min.js" type="text/javascript"></script>

        <script src="<?php echo base_url('admin');?>/assets/plugins/jquery-multi-select/jquery.multi-select.js" type="text/javascript"></script>
        <script src="<?php echo base_url('admin');?>/assets/plugins/jquery-multi-select/jquery.quicksearch.js" type="text/javascript"></script>
        <script src="<?php echo base_url('admin');?>/assets/plugins/bootstrap-inputmask/bootstrap-inputmask.min.js" type="text/javascript"></script>
        <script src="<?php echo base_url('admin');?>/assets/plugins/bootstrap-select/bootstrap-select.min.js" type="text/javascript"></script>
        <script src="<?php echo base_url('admin');?>/assets/plugins/spinner/spinner.min.js" type="text/javascript"></script>
        <script src="<?php echo base_url('admin');?>/assets/plugins/select2/select2.min.js" type="text/javascript"></script>
        <script src="<?php echo base_url('admin');?>/assets/pages/jquery.form-advance.init.js" type="text/javascript"></script>
        <script src="<?php echo base_url('admin');?>/assets/js/jquery.app.js"></script>
   
        <?php echo $this->renderSection('js');?>
    </body>
</html>
