<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="Mannat Themes">
        <meta name="keyword" content="">

        <title>Sae App | Login</title>

        <!-- Theme icon -->
        <link rel="shortcut icon" href="<?php echo base_url('/admin/');?>/assets/images/favicon.ico">

        <!-- Theme Css -->
        <link href="<?php echo base_url('/admin/');?>/assets/css/bootstrap.min.css" rel="stylesheet">
        <link href="<?php echo base_url('/admin/');?>/assets/css/slidebars.min.css" rel="stylesheet">
        <link href="<?php echo base_url('/admin/');?>/assets/css/icons.css" rel="stylesheet">
        <link href="<?php echo base_url('/admin/');?>/assets/css/menu.css" rel="stylesheet" type="text/css">
        <link href="<?php echo base_url('/admin/');?>/assets/css/style.css" rel="stylesheet">
    </head>

    <body class="sticky-header">
        <?= $this->renderSection('content') ?>   
        <script type="text/javascript">
            const baseApi = "<?php echo base_url('api');?>"
            const baseUrl = "<?php echo base_url();?>"
        </script>

        <!-- jQuery -->
        <script src="<?php echo base_url('/admin/');?>/assets/js/jquery-3.2.1.min.js"></script>
        <script src="<?php echo base_url('/admin/');?>/assets/js/popper.min.js"></script>
        <script src="<?php echo base_url('/admin/');?>/assets/js/bootstrap.min.js"></script>
        <script src="<?php echo base_url('/admin/');?>/assets/js/jquery-migrate.js"></script>
        <script src="<?php echo base_url('/admin/');?>/assets/js/modernizr.min.js"></script>
        <script src="<?php echo base_url('/admin/');?>/assets/js/jquery.slimscroll.min.js"></script>
        <script src="<?php echo base_url('/admin/');?>/assets/js/slidebars.min.js"></script>
        <script src="<?php echo base_url('/');?>/axios/dist/axios.min.js"></script>
        

        <!--app js-->
        <script src="<?php echo base_url('/admin/');?>/assets/js/jquery.app.js"></script>
        <?= $this->renderSection('js') ?>   
    </body>
</html>
